message:
    commandForPlayersOnly: This command is for online players only!
    pluginReloadedConsole: §aPlugin reloaded!
    pluginReloadedPlayer: §aPlugin reloaded!
    youGotThePrize: You got the prize!
    followPlayersGotThePrize: Success! The following player(s) got the prize:
    wrongValueByPlayers: 
    wrongValueByProb: 
    cannotGiveAwayAir: Cannot give away air!