name: BukkitSimpleItemLottery
version: 0.0.1a
description: Simple item lottery for craftbukkit.
author: Saren
website: https://github.com/Shaorune/SimpleItemLottery/
 
main: hk.coms.wtako.BukkitSimpleItemLottery.Main
database: false
 
commands:
    silot:
        description: Basic command.
        usage: Type /<command> ? to get help.
        permission: silot.use
        permission-message: §cYou are not permitted to use this command!

permissions:
    silot.*:
        description: Gives access to all BukkitSimpleItemLottery commands.
        default: op
        children:
            silot.use: true
            silot.reload: true
    silot.use:
        description: Gives access to lottery commands.
        default: op
    silot.reload:
        description: Allows player to reload BukkitSimpleItemLottery.
        default: op